# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0002_auto_20171116_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wagering_requirement',
            field=models.IntegerField(default=10, max_length=3),
        ),
    ]
