# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0004_auto_20171122_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusWageredTransaction',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='spin.Transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bonus_wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_wager_transaction', to='spin.Wallet')),
                ('real_money_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spin.Wallet')),
            ],
        ),
    ]
